frontend:
	bash component/frontend.sh
mongodb:
	bash component/mongodb.sh
catalogue:
	bash component/catalogue.sh
redis:
	bash component/redis.sh
user:
	bash component/user.sh
cart:
	bash component/cart.sh